Introduction

NumPy (Numerical Python) is a powerful Python library used for numerical computing. It provides support for multidimensional arrays, mathematical operations, statistical functions, and efficient data processing. NumPy is the foundation of libraries such as Pandas, Scikit-learn, TensorFlow, and many Machine Learning frameworks.


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


Indexing
Explanation
Indexing is used to access individual elements of an array.
NumPy uses zero-based indexing.
Negative indexing accesses elements from the end.


In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[3])
print(arr[-1])

10
40
50


Reshape
Explanation
The reshape() function changes the shape of an array without changing its data.
It is useful for converting one-dimensional arrays into two-dimensional arrays.


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


Broadcasting
Explanation
Broadcasting allows NumPy to perform operations on arrays of different shapes.
It automatically expands smaller arrays to match larger arrays during operations.
Broadcasting reduces the need for loops.

In [6]:
import numpy as np

arr = np.array([10,20,30])

result = arr + 5

print(result)

[15 25 35]


Mathematical Operations
Explanation
NumPy supports fast mathematical operations on arrays.
Operations are performed element by element.

In [7]:
import numpy as np

arr = np.array([10,20,30])

print(arr + 5)
print(arr * 2)
print(arr / 2)

[15 25 35]
[20 40 60]
[ 5. 10. 15.]


Statistics
Explanation
NumPy provides built-in statistical functions.
These functions help analyze numerical data quickly.

In [8]:
import numpy as np

marks = np.array([75,80,90,65,85])

print(np.max(marks))
print(np.min(marks))
print(np.mean(marks))

90
65
79.0


Random Numbers
Explanation
NumPy can generate random numbers for simulations, testing, and Machine Learning.
The random module is used to create random integers and arrays.

In [9]:
import numpy as np

random_numbers = np.random.randint(1,100,5)

print(random_numbers)

[84 87 40 43 54]
